# Generated by Django 3.1.5 on 2021-06-29 22:17

import cms.fields
import cms.mixins
import django.db.models.deletion
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", cms.fields.CharField()),
                ("slug", cms.fields.SlugField(unique=True)),
                ("number", cms.fields.PositiveIntegerField()),
                ("menu", cms.fields.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "page",
                "verbose_name_plural": "pages",
                "ordering": ["number"],
                "abstract": False,
            },
            bases=(cms.mixins.Numbered, models.Model),
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", cms.fields.CharField()),
                ("type", cms.fields.CharField()),
                ("number", cms.fields.PositiveIntegerField()),
                ("content", cms.fields.TextField()),
                ("image", cms.fields.ImageField()),
                (
                    "video",
                    embed_video.fields.EmbedVideoField(
                        blank=True,
                        help_text="Paste a YouTube, Vimeo, or SoundCloud link",
                        verbose_name="video",
                    ),
                ),
                ("href", cms.fields.CharField()),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sections",
                        to="website.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "section",
                "verbose_name_plural": "sections",
                "ordering": ["number"],
                "abstract": False,
            },
            bases=(cms.mixins.Numbered, models.Model),
        ),
        migrations.CreateModel(
            name="SectionImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="", verbose_name="Image")),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="website.section",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
    ]
